funnyquiz/urls.py
from django.conf.urls import url

from . import views

app_name = 'funnyquiz'
urlpatterns = [
	url(r'^$', views.quizList, name='quiz_index'),
	url(r'^(?P<quiz_url>[^/]+)/$', views.quizWelcome, name='quiz_welcome'),
    url(r'^(?P<quiz_url>[^/]+)/result/$', views.quizResult,
		name='quiz_result'),
]

funnyquizsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^uoftquiz/', include('funnyquiz.urls')),
]

funnyquiz/models.py
from django.db import models


# Create your models here.
class Quiz(models.Model):
    QuizName = models.CharField(max_length=50)
    QuizUrl = models.CharField(max_length=200)
    UseStandardWelcomePage = models.BooleanField(default=True)
    WelcomeMessage = models.CharField(max_length=200)
    WelcomeImage = models.FileField(null=True, blank=True)
    UseStandardResultPage = models.BooleanField(default=True)
    CreatedTime = models.DateField()

    def __str__(self):
        return str(self.pk) + ' - ' + str(self.QuizName)


class Question(models.Model):
    Quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    QuestionText = models.CharField(max_length=200)
    '''QuestionHasImage = models.BooleanField(default=False)'''
    QuestionImage = models.FileField(null=True, blank=True)
    

    def __str__(self):
        return str(self.pk) + ' - ' + self.QuestionText


class Answer(models.Model):
    ParentQuestion = models.ForeignKey(Question, on_delete=models.CASCADE)
    AnswerText = models.CharField(max_length=100)
    AnswerImg = models.FileField(null=True, blank=True)
    '''AnswerHasImage = models.BooleanField(default=False)'''
    IsCorrectAnswer = models.BooleanField(default=False)

    def __str__(self):
        return self.AnswerText

class Quizstate(models.Model):
    Quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    VisitorCount = models.IntegerField()
    CompletionCount = models.IntegerField()
    AvgCorrecteness = models.FloatField()
    StdDev = models.FloatField()

funnyquiz/views.py
# -*- coding: UTF-8 -*-

import pdb; pdb.set_trace()

from .models import *
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from datetime import datetime
from datetime import timedelta
from django.utils import translation

import random;


# Create your views here.
def quizList(request):
    quizes = Quiz.objects.all()
    context = {'quizes' : quizes}
    return render(request, 'funnyquiz/quiz_list.html', context)


def quizWelcome(request, quiz_url):
    #for quiz in GetQuizList():
    #    if quiz.QuizUrl == quiz_url:
    #        cur_quiz = quiz
    cur_quiz = get_object_or_404(Quiz, QuizUrl=quiz_url)
    if request.method == 'GET':
        time_clicked_str = request.COOKIES.get('clicked')
        print(time_clicked_str)
        time_clicked = 0
        time_clicked_str = request.COOKIES.get('clicked')
    elif request.method == 'POST':
        time_clicked_str = request.COOKIES.get('clicked')
        time_clicked = int(time_clicked_str)
        answer_id_selected = request.POST.get("answer", "")
        answer_selected = get_object_or_404(Answer, pk=int(answer_id_selected))
        if (answer_selected.IsCorrectAnswer):
            time_clicked += 1
        '''correct_answer = random.choice(("answer1", "answer2", "answer3", "answer4"))
        if request.POST.get(correct_answer, ""):
            time_clicked += 1'''
    '''request.session['clicked'] = time_clicked'''
    next_question = random.choice(cur_quiz.question_set.all())
    
    context = {'cur_quiz' : cur_quiz, 'time_clicked' : time_clicked, 'this_question': next_question}
    response = render(request, 'funnyquiz/quiz_welcome.html', context)
    response.set_cookie('clicked', time_clicked)
    return response


def quizResult(request, quiz_url):
    cur_quiz = get_object_or_404(Quiz, QuizUrl=quiz_url)
    cur_quizstate = cur_quiz.quizstate_set.filter(id=1)
    context = {'cur_quiz' : cur_quiz, 'cur_quizstate' : cur_quizstate}
    response = render(request, 'funnyquiz/quiz_result.html', context)
    return response


'''def GetQuizList():
    q1 = Quiz("Qz001", "你TM真的是多大的么", "true_UofTer", True, "聪明的你，来看看你到底是不是多大的吧", None, True, datetime.now(None))
    q2 = Quiz("Qz002", "你TM根本不是多大的", "fake_UofTer", True, "傻乎乎的你，肯定不是多大的", None, True, datetime.now() + timedelta(minutes = 10))
    return [q1, q2]



class Quiz:

    def __init__(self, QuizId, QuizName, QuizUrl,
                UseStandardWelcomePage, WelcomeMessage, WelcomeImage,
                UseStandardResultPage, CreatedTime):
        self.QuizId = QuizId
        self.QuizName = QuizName
        self.QuizUrl = QuizUrl
        self.UseStandardWelcomePage = UseStandardWelcomePage
        self.WelcomeMessage = WelcomeMessage
        self.WelcomeImage = WelcomeImage,
        self.UseStandardResultPage = UseStandardResultPage
        self.CreatedTime = CreatedTime
'''

funnyquiz/templates/funnyquiz/base.html
<!--
Generic Blueprint
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}UofTer Quiz{% endblock %}</title>
    {% load staticfiles %}
    <!-- Put bootstrap in the first place -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'funnyquiz/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'funnyquiz:quiz_index' %}">UofTer</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'funnyquiz:quiz_index' %}">
                            <span class="glyphicon glyphicon-pencil"
                                  aria-hidden="true"></span>&nbsp; Quizes
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-right" role="search" method="get" action="{% url 'funnyquiz:quiz_index' %}">
                    <div class="form-group">
                        <input type="text" class="form-control" name="query" value="{{ request.GET.query }}">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
            </div>

        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

funnyquiz/templates/funnyquiz/quiz_list.html
{% extends 'funnyquiz/base.html' %}
{% block body %}
	<h1> Quiz List! </h1>
	<ul>
	{% for quiz in quizes %}
		<li><a href="{% url 'funnyquiz:quiz_welcome' quiz.QuizUrl %}"> {{quiz.QuizName}} </a>
		</li>
	{% endfor %}
	</ul>
{% endblock %}

funnyquiz/templates/funnyquiz/quiz_result.html
{% extends 'funnyquiz/base.html' %}
{% block title %}Result{% endblock %}

{% block body %}
<h1>{{ cur_quiz.QuizName }}</h1>
<ul>
    <li>{{ cur_quizstate.VisitorCount }}</li>
    <li>{{ cur_quizstate.CompletionCount }}</li>
</ul>
<a href="{% url 'funnyquiz:quiz_welcome' cur_quiz.QuizUrl %}">Play again?</a>
{% endblock %}

funnyquiz/templates/funnyquiz/quiz_welcome.html
{% extends 'funnyquiz/base.html' %}
{% block title %}Get Ready!{% endblock %}

{% block body %}
	<h1> Get Ready For Quiz </h1>

	<body>
		<p> {{cur_quiz.QuizName}} </p>
		<p> {{this_question.QuestionText}} </p>
		<form action = "{%url 'funnyquiz:quiz_welcome' cur_quiz.QuizUrl%}"
			  method = "post">
			{% csrf_token %}
			{% for answer in this_question.answer_set.all %}
			<button type="submit" name="answer" value="{{answer.id}}"> {{answer.AnswerText}} </button>
		</br>
			{% endfor %}



			<!--<button type="submit" name="answer1" value="1"> Answer 1 </button>-->
		</form>
		<!--<form action = "{%url 'funnyquiz:quiz_welcome' cur_quiz.QuizUrl%}"
			  method = "post">
			{% csrf_token %}
			<button type="submit" name="answer2" value="2"> Answer 2 </button>
		</form>
		<form action = "{%url 'funnyquiz:quiz_welcome' cur_quiz.QuizUrl%}"
			  method = "post">
			{% csrf_token %}
			<button type="submit" name="answer3" value="3"> Answer 3 </button>
		</form>
		<form action = "{%url 'funnyquiz:quiz_welcome' cur_quiz.QuizUrl%}"
			  method = "post">
			{% csrf_token %}
			<button type="submit" name="answer4" value="4"> Answer 4 </button>
		</form>-->
		<p> {{time_clicked}} </p>
		<form action="{% url 'funnyquiz:quiz_result' cur_quiz.QuizUrl %}"
			  method="post">
			{% csrf_token %}
			<input type="submit" value="See result" />
		</form>
	</body>
{% endblock %}